---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{pipeline_name}}
spec:
  params:
    - name: repo_url
    - name: revision
  workspaces:
    - name: source
    {%if workspaces -%}
    {% for workspace in workspaces -%}
    - name: {{ workspace }}
    {% endfor -%}
    {% endif -%}
{%- if resources %}
  resources:
    {% for resource in resources -%}
    - name: {{ resource[1] }}
      type: {{ resource[0] }}
    {% endfor %}
  {% endif %}
  tasks:
{% filter indent(width=4) %}
{% for step in steps -%}
{{ step }}
{% endfor -%}
{% endfilter %}
  finally:
    - name: finally
      taskSpec:
        steps:
          - name: send-to-slack
            env:
              - name: SLACK_WEBHOOK_URL
                valueFrom:
                  secretKeyRef:
                    name: slack-tektoncd-ci-webhook
                    key: hook_url
              - name: PIPELINERUN
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tekton.dev/pipelineRun']
              {% raw -%}
              - name: GITHUB_PULL_LABEL
                value: "{{pull_request.labels}}"
              - name: LABEL_TO_CHECK
                value: "nightly-ci"
              - name: SUCCESS_URL_ICON
                value: "https://github.com/tektoncd.png"
              - name: FAILURE_URL_ICON
                value: "https://www.vhv.rs/dpng/d/415-4154815_grumpy-cat-png-photos-grumpy-cat-png-transparent.png"
              - name: SUCCESS_SUBJECT
                value: "Pipelines Catalog CI ran successfull on {{pull_request.html_url}} :pipelinedance: :dancing-penguin: :yay2:"
              - name: FAILURE_SUBJECT
                value: "Pipelines Catalog CI has failed on {{pull_request.html_url}} :fb-sad: :crying_cat_face: :crying:"
              - name: LOG_URL
                value: "{{openshift_console_pipelinerun_href}}"
              {% endraw %}
            image: quay.io/chmouel/tekton-asa-code:latest
            command: ["/code/misc/send-slack-notifications.py"]
            
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: {{pipeline_name}}-run
spec:
  {% if serviceAccountName -%}
  serviceAccountName: {{serviceAccountName}}
  {% endif %}
  pipelineRef:
    name: {{pipeline_name}}
  params:
    {% raw -%}
    - name: repo_url
      value: {{repo_url}}
    - name: revision
      value: {{revision}}
    {% endraw %}
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
  {%if workspaces %}
    {% for workspace in workspaces -%}
    - name: {{ workspace }}
      persistentvolumeclaim:
        claimName: {{workspace}}
    {% endfor %}
  {% endif %}
  {%if resources %}
  resources:
    {% for resource in resources -%}
    - name: {{ resource[1] }}
      resourceRef:
        name: {{resource[1]}}
    {% endfor %}
  {% endif %}
