---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s2i-perl-pr-repo
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/sclorg/s2i-perl-container
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s2i-perl-pr-image
spec:
  type: image
  params:
    - name: url
      value: "image-registry.openshift-image-registry.svc:5000/{{namespace}}/s2i-perl-pr"
